# Generated by Django 3.2.20 on 2023-07-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiki_h', '0002_auto_20230731_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feed',
            new_name='Feeds',
        ),
    ]
