# Generated by Django 3.2.20 on 2023-08-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiki_h', '0003_rename_feed_feeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.TextField()),
                ('profile_image', models.TextField()),
                ('user_id', models.TextField()),
                ('like_count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Feeds',
        ),
    ]
